# Generated by Django 3.0.6 on 2020-06-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200604_1615'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Color'),
            preserve_default=False,
        ),
    ]
