# Generated by Django 3.0.6 on 2020-06-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200604_1929'),
        ('orders', '0003_auto_20200604_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='authentication.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
