# Generated by Django 3.0.6 on 2020-06-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200604_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building_address',
        ),
    ]
