# Generated by Django 3.0.6 on 2020-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=32, unique=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('color', models.CharField(max_length=32)),
                ('color_en', models.CharField(max_length=32, null=True)),
                ('color_hy', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description_hy', models.CharField(blank=True, max_length=200, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('size_description', models.CharField(max_length=32)),
                ('size_description_en', models.CharField(max_length=32, null=True)),
                ('size_description_hy', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessorie',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('type', models.CharField(max_length=64)),
                ('type_en', models.CharField(max_length=64, null=True)),
                ('type_hy', models.CharField(max_length=64, null=True)),
                ('material', models.CharField(max_length=64)),
                ('material_en', models.CharField(max_length=64, null=True)),
                ('material_hy', models.CharField(max_length=64, null=True)),
            ],
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2)),
                ('sex_en', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2, null=True)),
                ('sex_hy', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2, null=True)),
                ('style', models.CharField(choices=[('Athletic', 'athletic'), ('Boots', 'boots'), ('Classic', 'classic')], default='Classic', max_length=64)),
                ('material_inner', models.CharField(max_length=64)),
                ('material_inner_en', models.CharField(max_length=64, null=True)),
                ('material_inner_hy', models.CharField(max_length=64, null=True)),
                ('material_outer', models.CharField(max_length=64)),
                ('material_outer_en', models.CharField(max_length=64, null=True)),
                ('material_outer_hy', models.CharField(max_length=64, null=True)),
                ('outsole', models.CharField(max_length=32)),
                ('outsole_en', models.CharField(max_length=32, null=True)),
                ('outsole_hy', models.CharField(max_length=32, null=True)),
                ('season', models.CharField(blank=True, max_length=16)),
                ('season_en', models.CharField(blank=True, max_length=16, null=True)),
                ('season_hy', models.CharField(blank=True, max_length=16, null=True)),
                ('sizes', models.ManyToManyField(related_name='shoes', to='core.Size')),
            ],
            bases=('core.product',),
        ),
    ]
