# Generated by Django 3.0.6 on 2020-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Արական', 'Male'), ('Իգական', 'Female')], default='Արական', max_length=12),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sex_en',
            field=models.CharField(choices=[('Արական', 'Male'), ('Իգական', 'Female')], default='Արական', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sex_hy',
            field=models.CharField(choices=[('Արական', 'Male'), ('Իգական', 'Female')], default='Արական', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(choices=[('Աթլետիկ', 'athletic'), ('Երկարաճիտք', 'boots'), ('Դասական', 'classic')], default='Դասական', max_length=64),
        ),
    ]
