# Generated by Django 3.0.6 on 2020-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200607_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='style_en',
            field=models.CharField(choices=[('Athletic', 'Աթլետիկ'), ('Boots', 'Երկարաճիտք'), ('Classic', 'Դասական')], default='Classic', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='style_hy',
            field=models.CharField(choices=[('Athletic', 'Աթլետիկ'), ('Boots', 'Երկարաճիտք'), ('Classic', 'Դասական')], default='Classic', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(choices=[('Athletic', 'Աթլետիկ'), ('Boots', 'Երկարաճիտք'), ('Classic', 'Դասական')], default='Classic', max_length=64),
        ),
    ]
