# Generated by Django 3.0.6 on 2020-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200607_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=12),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sex_en',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sex_hy',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('boots', 'Boots'), ('classic', 'Classic')], default='classic', max_length=64),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style_en',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('boots', 'Boots'), ('classic', 'Classic')], default='classic', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style_hy',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('boots', 'Boots'), ('classic', 'Classic')], default='classic', max_length=64, null=True),
        ),
    ]
