# Generated by Django 3.0.6 on 2020-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200607_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='sex_en',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sex_hy',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='style_en',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='style_hy',
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=12),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('boots', 'Boots'), ('classic', 'Classic')], default='Classic', max_length=64),
        ),
    ]
