XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX
    BBBB BBBBBB
    BBBB BBBBBB BBBB

    XXXXXXX XXXXXXX XXXX XXXXXXX XX XXXXXXXXX XXX XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX

    XXXXX XXXXXXXXXXXXXXXX

    XXXXXXX XXX XXXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XX

    XXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXX XXXXXX XXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBB

    XXXXXXXBBBBB BBBBBBBBBBBBBXXXXXXXX
XXXXXXX

XXXXXX
    BBBBB BBBBBBBBBBBB
    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                
            XXXXXX
        XXXXXX
        XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXXXXXXXX
        BBBBBB
    BBBBB
XXXXXXX
