BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
 gettext(u'Order History') 
BBBBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXXXX XXXXXX X XXXX
        BBB BBBB BB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XXXXXXXX XXXX
                XXXXXXXXX XXXX
                XXXXXXX XXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXX
                XXXXXXXXX BBBB BBBBBBBBFFFFFFFF XXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX
        BBBBBB
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXX FFFFFFF FF FFXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                XXXXXXXXX BBBB BBBBBBBB FFFFFFFF XXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
                BB BBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXX
                XXXXXX
                BBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
            XXXXXX
            BB BBB BBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                    XXXX XX XXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
    BBBBBB
XXXXXX
BBBBBBBB